language: go

go:
  - master

install:
  - go get ./...
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint

script:
  - go vet ./...
  - diff <(goimports -d .) <(printf "")
  - diff <(golint ./...) <(printf "")
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./build.sh doctest-junit-report

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - "dist/darwin_386_doctest-junit-report.zip"
    - "dist/darwin_64_doctest-junit-report.zip"
    - "dist/linux_386_doctest-junit-report.zip"
    - "dist/linux_64_doctest-junit-report.zip"
    - "dist/windows_386_doctest-junit-report.zip"
    - "dist/windows_64_doctest-junit-report.zip"
  on:
    all_branches: true
    tags: true
